src/app/(blog-pages)/blog/page.tsx
Initially, I implemented the deleteBlog function, but it exhibited a logical flaw. Recognizing the issue, I refined the logic by employing state manipulation with the useState hook, resolving the problem and ensuring the correct deletion of blogs based on filenames.
=> Resolve state manipulation issue in deleteBlog function

apps/buildog/src/app/(blog-pages)/layout.tsx, apps/buildog/src/components/app-bar.tsx, apps/buildog/src/components/user-auth-form.tsx, packages/ui/components/ui/avatar.tsx, packages/ui/components/ui/dropdown-menu.tsx, packages/ui/package.json, packages/web-sdk/authenticator.ts, pnpm-lock.yaml
I also refactor user login form if not require i can change it asap
=> feat: add header to the main layout for displaying user avatar

packages/editor/src/Editor.tsx, packages/editor/src/components/RichText.tsx, packages/editor/src/components/index.tsx
Text editor is not working properly!
=> feat: first version of rich text editor

README.md
Added the paragraphs to README file for navigating the users to our wiki and added a paragraph for stating our objective for this project. Closes #45
=> docs: add wiki links in readme

apps/buildog/src/app/organizations/[organizationId]/layout.tsx, apps/buildog/src/components/app-bar.tsx, apps/buildog/src/components/org-navigation.tsx, apps/buildog/src/components/sidebar.tsx
edited the appbar to include a dropdown of user's organizations and a button to navigating to "/organizations" also deleted the button from the sidebar. Closes #81
=> feat(buildog): dropdown for switching organizations

apps/buildog/src/app/organizations/[organizationId]/settings/page.tsx, apps/buildog/src/components/user-table.tsx, packages/ui/components/ui/data-table.tsx
Added a table for managing users signed in for organizations also changed a little typo for our data table. Closes #89 
**Additional:** 
We currently have no component for our "blog" page where we show "there is no blogs yet" kind of text like in the "organizations" or "users" so I would like to take it or it can be opened as a "good-first-issue"
=> feat(buildog): user table for managing users

apps/api/internal/api/api.go, apps/api/internal/api/users.go, apps/api/internal/models/user.go, apps/api/internal/repository/user.go, apps/buildog/src/app/account/settings/profile/page.tsx
=> feat(api): user information 

.gitignore, apps/buildog/src/app/organizations/[organizationId]/web/page.tsx, apps/buildog/src/components/cards/date-card.tsx, apps/buildog/src/components/cards/default-card.tsx, apps/buildog/src/components/cards/feature-rich-card.tsx, apps/buildog/src/components/cards/image-card.tsx, apps/buildog/src/components/footers/default-footer.tsx, apps/buildog/src/components/footers/enhanced-footer.tsx, apps/buildog/src/components/footers/links-center-footer.tsx, apps/buildog/src/components/user-auth-form.tsx
=> feat(buildog): custom footer for theme

apps/api/internal/api/api.go, apps/api/internal/api/users.go, apps/api/internal/repository/user.go, apps/buildog/src/app/account/settings/profile/page.tsx, apps/buildog/src/components/user-sign-up-form.tsx
=> feat(api): add updateUserHandler to handle user updates

apps/api/internal/api/api.go, apps/api/internal/api/organization_user.go, apps/api/internal/api/organization_user_routes.go, apps/api/internal/models/organization_user.go, apps/api/internal/repository/organization_user.go
Closes #102
**Remaining CRUD operations has been implemented.**
=> feat(api): organization users crud

.github/workflows/Build-Docs.yml, .github/workflows/asd.yml, apps/api/internal/api/api.go, apps/api/internal/api/organization_user_routes.go, apps/api/internal/api/organizations.go, apps/api/internal/models/organization.go, apps/api/internal/repository/organization.go
=> feat(api): organization update and delete

.github/workflows/Build-Docs.yml, apps/docs/buildspec.yml
=> feat(docs): deployment for every update #125

apps/buildog/src/components/organizations-header.tsx, packages/ui/styles/global.css
=> feat(buildog): changed theme to zinc

apps/buildog/src/app/account/settings/appearance/page.tsx, apps/buildog/src/app/layout.tsx
=> feat(buildog): add system theme option to appearance settings

apps/docs/pages/getting-started/_meta.json, apps/docs/pages/getting-started/database.mdx, apps/docs/pages/getting-started/prerequisites.md
=> feat(docs): add documentation for prerequisites

apps/buildog/src/app/account/settings/appearance/page.tsx, apps/buildog/src/app/organizations/[organizationId]/(main)/blog/page.tsx, apps/buildog/src/app/organizations/[organizationId]/(main)/settings/page.tsx, apps/buildog/src/app/organizations/page.tsx, apps/buildog/src/components/account-sidebar.tsx, apps/buildog/src/components/avatar-dropdown.tsx, apps/buildog/src/components/drag-drop-list.tsx, apps/buildog/src/components/footers/enhanced-footer.tsx, apps/buildog/src/components/footers/links-center-footer.tsx, apps/buildog/src/components/org-navigation.tsx, apps/buildog/src/components/organization-user-modal.tsx, apps/buildog/src/components/sidebar.tsx, apps/buildog/src/components/themes/default-header.tsx, apps/buildog/src/components/themes/links-center-header.tsx, apps/buildog/src/components/themes/name-center-header.tsx, apps/buildog/src/components/user-auth-form.tsx, apps/buildog/src/components/user-sign-up-form.tsx, apps/buildog/src/components/user-table.tsx, packages/ui/components/ui/command.tsx, packages/ui/components/ui/context-menu.tsx, packages/ui/components/ui/dialog.tsx, packages/ui/components/ui/dropdown-menu.tsx, packages/ui/components/ui/menubar.tsx, packages/ui/components/ui/react-icons.tsx, packages/ui/components/ui/select.tsx, packages/ui/components/ui/sheet.tsx, packages/ui/components/ui/toast.tsx, packages/ui/package.json, pnpm-lock.yaml
- changed Radix icons to Phosphor icons.
=> refactor(buildog): change Radix icons to Phosphor icons

apps/buildog/src/app/organizations/[organizationId]/(main)/blog/page.tsx
closes [#146](https://github.com/buildog-dev/buildog/issues/146)
=> feat(buildog): enhance tags display and add tags column to blog page

apps/buildog/src/components/app-bar.tsx, apps/buildog/src/components/sidebar-organization-select.tsx, apps/buildog/src/components/sidebar.tsx
- Organization selection moved to sidebar. #155
=> feat(buildog): move organization selection on sidebar

apps/buildog/src/app/(auth)/layout.tsx, apps/buildog/src/components/auth-provider.tsx
fetch user information only if the current auth state doesn't have the user's information, requested by @kuzeykose
=> fix(buildog): fetch user information depending on current state

apps/api/internal/api/organization_user.go, apps/api/internal/auth/middleware.go, apps/api/internal/auth/permissions.go, apps/api/internal/models/role.go, apps/api/internal/repository/organization_user.go, apps/api/pkg/utils/request.go
=> fix(api): limit organization owner requests under organization_users 
